/*
  A try block can reside in a function.
*/

#include <iostream>
using namespace std;

int main() {


}