// A simple exception handling example.

#include <iostream>
using namespace std;

int main() {

	cout << "start\n";

	// Program statements that you want to monitor for exceptions are contained in a try block.
	try
	{

	}
	catch (const std::exception &)
	{

	}

}